version: "3.8"

services:
  eegfaktura-postgresql:
    image: ghcr.io/eegfaktura/eegfaktura-postgresql:0.1.0
    hostname: eegfaktura-postgresql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD_FILE: "/run/secrets/eegfaktura-postgres-password"
      POSTGRES_DATABASE: "postgres"
      DB_USERNAME: "eegfaktura"
      DB_PASSWORD_FILE: "/run/secrets/eegfaktura-db-password"
      DB_DATABASE: "eegfaktura"
      KEYCLOAK_DB_USERNAME: "keycloak"
      KEYCLOAK_DB_PASSWORD_FILE: "/run/secrets/eegfaktura-keycload-db-password"
      KEYCLOAK_DB_DATABASE: "keycloak"
      POSTGRES_INITDB_ARGS: "--locale=de_DE:UTF8"
    volumes:
      - eegfaktura_postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: "PGPASSWORD=$${DB_PASSWORD} pg_isready -d $${DB_DATABASE} -U $${DB_USERNAME} && psql --d $${DB_DATABASE} -U $${DB_USERNAME} --list"
      timeout: 10s
      start_period: 10s
      interval: 10s
      retries: 20
    secrets:
      - eegfaktura-postgres-password
      - eegfaktura-db-password
      - eegfaktura-keycload-db-password

  eegfaktura-mosquitto:
    image: ghcr.io/eegfaktura/eegfaktura-mosquitto:0.1.0
    hostname: eegfaktura-mosquitto
    command: /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf
    volumes:
      - eegfaktura_mosquitto_data:/mosquitto/data
      - eegfaktura_mosquitto_log:/mosquitto/log


  eegfaktura-postfix:
    image: ghcr.io/eegfaktura/eegfaktura-postfix:0.1.0
    hostname: eegfaktura-postfix
    environment:
      POSTFIX_RELAY_HOST: "smtp.yourdomain.com"
      POSTFIX_RELAY_PORT: "587"
      POSTFIX_RELAY_TLS: "yes"
      POSTFIX_RELAY_USER: "yoruser@yourdomain.com"
      POSTFIX_RELAY_PASSWORD_FILE: "/run/secrets/eegfaktura-smtp-password"
      POSTFIX_RELAY_EMAIL: "eegfaktura@yourdomain.com"
      POSTFIX_HOSTNAME: "eegfaktura-postfix"
      POSTFIX_MYDOMAIN: "yourdomain.com"
      POSTFIX_MYNETWORK: ""
      POSTFIX_DNS_1: "9.9.9.9"
      POSTFIX_DNS_2: "1.1.1.1"
    secrets:
      - eegfaktura-smtp-password

  eegfaktura-energystore:
    image: ghcr.io/eegfaktura/eegfaktura-energystore:0.1.0
    hostname: eegfaktura-energystore
    volumes:
      - eegfaktura_energystore_data:/opt/rawdata
    depends_on:
      - eegfaktura-mosquitto
    secrets:
      - eegfaktura-jwt-public-key

  eegfaktura-eda:
    image: ghcr.io/eegfaktura/eegfaktura-eda:0.1.0
    hostname: eegfaktura-eda
    volumes:
      - eegfaktura_eda_data:/storage
    depends_on:
      eegfaktura-postgresql:
        condition: service_healthy
      eegfaktura-mosquitto:
        condition: service_started
      eegfaktura-postfix:
        condition: service_started

  eegfaktura-backend:
    image: ghcr.io/eegfaktura/eegfaktura-backend:0.1.0
    hostname: eegfaktura-backend
    volumes:
      - eegfaktura_backend_data:/opt/storage
    depends_on:
      eegfaktura-postgresql:
        condition: service_healthy
      eegfaktura-mosquitto:
        condition: service_started
    secrets:
      - eegfaktura-jwt-public-key

  eegfaktura-filestore:
    image: ghcr.io/eegfaktura/eegfaktura-filestore:0.1.0
    hostname: eegfaktura-filestore
    volumes:
      - eegfaktura_filestore_data:/eegfaktura-filestore-data
    environment:
      DB_HOSTNAME: "eegfaktura-postgresql"
      DB_USERNAME: "eegfaktura"
      DB_PASSWORD_FILE: "/run/secrets/eegfaktura-db-password"
      HTTP_PROTOCOL: "http"
      HTTP_HOSTNAME: "0.0.0.0"
      HTTP_PORT: 8080
      HTTP_FILE_DL_ENDPOINT: "filestore"
      FILESTORE_LOCAL_BASE_DIR: "/eegfaktura-filestore-data"
      FILESTORE_CREATE_UNKNOWN_CATEGORY: "true"
      FILESTORE_CREATE_UNKNOWN_CONTAINER: "true"
      FILESTORE_CREATE_UNKNOWN_STORAGE: "true"
    depends_on:
      eegfaktura-postgresql:
        condition: service_healthy
    secrets:
      - eegfaktura-db-password

  eegfaktura-billing:
    image: ghcr.io/eegfaktura/eegfaktura-billing:0.1.0
    hostname: eegfaktura-billing
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://eegfaktura-postgresql:5432/eegfaktura"
      JDBC_DATABASE_USERNAME: "eegfaktura"
      JDBC_DATABASE_PASSWORD: "Dzy5lShLn1N3rqTM"
    depends_on:
      eegfaktura-postgresql:
        condition: service_healthy
      eegfaktura-postfix:
        condition: service_started

  eegfaktura-web:
    image: eegfaktura-web:latest # This needs updated with new version in my PR. 
    hostname: eegfaktura-web
    environment:
      REACT_APP_AUTH_SERVER_URL: https://localhost/auth/  # This does not work but it would be great if it did...
    depends_on:
      - eegfaktura-backend
      - eegfaktura-energystore
      - eegfaktura-billing
      - eegfaktura-filestore

  eegfaktura-proxy:
    image: ghcr.io/eegfaktura/eegfaktura-proxy:0.1.0
    hostname: eegfaktura-proxy
    ports:
      - "443:443"
    environment:
      KEY_FILE: /run/secrets/eegfaktura-https-key
      CERT_FILE: /run/secrets/eegfaktura-https-cert
    depends_on:
      - eegfaktura-web
      - eegfaktura-backend
      - eegfaktura-energystore
      - eegfaktura-billing
      - eegfaktura-filestore
      - eegfaktura-keycloak
    secrets:
      - eegfaktura-https-key
      - eegfaktura-https-cert

  eegfaktura-keycloak:
    image: eegfaktura-keycloak:latest # This image need re-built and updated to quay.io/keycloak/keycloak:latest
    hostname: eegfaktura-keycloak
    environment:
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "Rs7naJnwoM4cz5Ws"
      KC_DB_URL: "jdbc:postgresql://eegfaktura-postgresql:5432/keycloak"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "SuperSecretPassword"
      KC_HOSTNAME: "https://localhost/auth/"
    depends_on:
      eegfaktura-postgresql:
        condition: service_healthy

volumes:
    eegfaktura_postgres_data:
    eegfaktura_mosquitto_data:
    eegfaktura_mosquitto_log:
    eegfaktura_energystore_data:
    eegfaktura_eda_data:
    eegfaktura_backend_data:
    eegfaktura_filestore_data:

secrets:
  eegfaktura-postgres-password:
    file: ./eegfaktura-postgres-password.txt
  eegfaktura-db-password:
      file: ./eegfaktura-db-password.txt
  eegfaktura-jwt-public-key:
    file: ./jwt-public-key.pem
  eegfaktura-https-key:
    file: ./eegfaktura-proxy.key
  eegfaktura-https-cert:
    file: ./eegfaktura-proxy.crt
  eegfaktura-smtp-password:
      file: ./eegfaktura-smtp-password.txt
  eegfaktura-keycload-db-password:
      file: ./eegfaktura-keycload-db-password.txt
